name: Build sdist and wheel

on:
  workflow_call:
    inputs:
      CIBW_SKIP:
        required: true
        type: string
      CIBW_BUILD:
        required: true
        type: string
      CIBW_ARCHS_MACOS:
        required: false
        type: string
      CIBW_ARCHS_LINUX:
        required: false
        type: string
      CIBW_ARCHS_WINDOWS:
        required: false
        type: string
      VERSION:
        required: false
        type: string

jobs:
  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set correct version
        if: ${{ inputs.VERSION != '' }}
        run: echo -n "${{ inputs.VERSION }}" > VERSION
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        with:
          output-dir: wheelhouse
        env:
          CIBW_SKIP: ${{ inputs.CIBW_SKIP }}
          CIBW_BUILD: ${{ inputs.CIBW_BUILD }}
          CIBW_ARCHS_MACOS: ${{ inputs.CIBW_ARCHS_MACOS }}
          CIBW_ARCHS_LINUX: ${{ inputs.CIBW_ARCHS_LINUX }}
          CIBW_ARCHS_WINDOWS: ${{ inputs.CIBW_ARCHS_WINDOWS }}
      - name: List wheels
        run: ls -lah ./wheelhouse
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set correct version
        if: ${{ inputs.VERSION != '' }}
        run: echo -n "${{ inputs.VERSION }}" > VERSION
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
